import { Router } from 'express';
import { authRouter } from './auth.js';
import { healthRouter } from './health.js';
import { actionsRouter } from './actions.js';
import { alertsRouter } from './alerts.js';
import { adminRouter } from './admin.js';
import { arRouter } from './ar.js';
import { carbonBankRouter } from './carbon-bank.js';
import { challengesRouter } from './challenges.js';
import { clubsRouter } from './clubs.js';
import { coachRouter } from './coach.js';
import { communityRouter } from './community.js';
import { impactRouter } from './impact.js';
import { learningRouter } from './learning.js';
import { grantsRouter } from './grants.js';
import { jobsRouter } from './jobs.js';
import { offlineRouter } from './offline.js';
import { paymentsRouter } from './payments.js';
import { profilesRouter } from './profiles.js';
import { messagesRouter } from './messages.js';
import { verificationRouter } from './verification.js';
import { treeRouter } from './trees.js';
import { rewardsRouter } from './rewards.js';
import { marketplaceRouter } from './marketplace.js';

export const apiRouter = Router();

apiRouter.use('/health', healthRouter);
apiRouter.use('/auth', authRouter);
apiRouter.use('/profiles', profilesRouter);
apiRouter.use('/actions', actionsRouter);
apiRouter.use('/alerts', alertsRouter);
apiRouter.use('/admin', adminRouter);
apiRouter.use('/ar', arRouter);
apiRouter.use('/carbon-bank', carbonBankRouter);
apiRouter.use('/challenges', challengesRouter);
apiRouter.use('/clubs', clubsRouter);
apiRouter.use('/coach', coachRouter);
apiRouter.use('/community', communityRouter);
apiRouter.use('/learning', learningRouter);
apiRouter.use('/grants', grantsRouter);
apiRouter.use('/jobs', jobsRouter);
apiRouter.use('/offline', offlineRouter);
apiRouter.use('/payments', paymentsRouter);
apiRouter.use('/messages', messagesRouter);
apiRouter.use('/rewards', rewardsRouter);
apiRouter.use('/verification', verificationRouter);
apiRouter.use('/trees', treeRouter);
apiRouter.use('/impact', impactRouter);
apiRouter.use('/marketplace', marketplaceRouter);