name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 1. Set up Java environment
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 2. Set up Flutter SDK
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # 3. Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # 4. Build Release APK with the updated URL
      - name: Build Release APK
        run: flutter build apk --release --dart-define=GREENRES_API_BASE_URL=https://greenres.onrender.com/api/v1

      # 5. Upload finished APK as Artifact
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
          
